import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AnimationProvider } from "@/Context/AnimationContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Neno - Youtube Video to Audio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AnimationProvider>
        <body className={inter.className}>{children}</body>
      </AnimationProvider>
    </html>
  );
}
